from .templates import (
    MEETING_SUMMARY_SYSTEM,
    MEETING_SUMMARY_USER,
    STANDUP_SYSTEM,
    STANDUP_USER,
)

__all__ = [
    "MEETING_SUMMARY_SYSTEM",
    "MEETING_SUMMARY_USER",
    "STANDUP_SYSTEM",
    "STANDUP_USER",
]
